events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Backend API and WebSocket configuration
    upstream backend_api {
        server api:3000;
    }

    server {
        listen 80;
        server_name ticktack-tag.dam.inspedralbes.cat;

        # Increase upload size for skins/maps
        client_max_body_size 20M;

        # API Proxies
        location /api/ {
            proxy_pass http://backend_api/api/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache off;
        }

        # Health Check
        location /health {
            proxy_pass http://backend_api/health;
        }

        # FRONTEND + WEBSOCKET (Unificados)
        location / {
            # 1. Si es WebSocket (Unity), usar el bloque especial interno
            error_page 418 = @websocket;
            if ($http_upgrade = "websocket") {
                return 418;
            }

            # 2. Si es tráfico web normal (Navegador), servir archivos
            root /var/www/frontend;
            index index.html;
            try_files $uri $uri/ /index.html;
            
            gzip_static on;
        }

        # Bloque interno para proteger la conexión WebSocket de Unity
        location @websocket {
            proxy_pass http://backend_api;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}